
# About the project

*Write a short description about the course and add a link to your GitHub repository here. This is an R Markdown (.Rmd) file so you should use R Markdown syntax.*

```{r}
# This is a so-called "R chunk" where you can write R code.

date()

```

# Introduction
*"How are you feeling right now? What do you expect to learn? Where did you hear about the course?"*

I am extremely excited about this course! I have just started my PhD studies at the Institute of Atmospheric and Earth System Research. My research topic is related to building a framework for climate competencies, based mostly on interviews and surveys. Since my background is in natural sciences I have very little to no experience on behavioral sciences and their methodology. For this reason, I have chosen this course. It was suggested to me by our colleagues in the faculty of educational sciences.

*** 
I expect to learn to use R, which I'm not too worried about since I have experience in **Python**, and even more importantly, the statistical practices and rules that apply in human sciences, when it's not all about nature and numbers.

***

[My repository](https://github.com/joulasip/IODS-project.git)

As text: https://github.com/joulasip/IODS-project.git

